# Generated by Django 5.2 on 2025-05-04 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_notificationsettings_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='low_stock_reminders_enabled',
            new_name='lowStockRemindersEnabled',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='medication_reminders_enabled',
            new_name='medicationRemindersEnabled',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='minutes_before_scheduled_time',
            new_name='minutesBeforeScheduledTime',
        ),
    ]
