# Generated by Django 5.2 on 2025-05-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_low_stock_reminders_enabled_notificationsettings_lowstockremindersenabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photoUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
