# Generated by Django 5.2 on 2025-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
