# Generated by Django 5.2 on 2025-05-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_notificationsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationintake',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
