# Generated by Django 5.2 on 2025-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationintake',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='medicationintake',
            name='schedule',
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='medicationId',
            field=models.CharField(default=1234),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='scheduleId',
            field=models.CharField(default=1234),
            preserve_default=False,
        ),
    ]
