# Generated by Django 5.2 on 2025-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_medicationintake_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='medicationschedule',
            name='days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
