# Generated by Django 5.2 on 2025-05-16 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_medicationschedule_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='remaining_quantity',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='medication',
            name='lowStockThreshold',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='medication',
            name='remainingQuantity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='medication',
            name='totalQuantity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
